import { EvmBatchProcessor } from "@subsquid/evm-processor";
import { TypeormDatabase }   from "@subsquid/typeorm-store";
import { In }                from "typeorm";

// ─── ABI event topics (keccak256 of signature) ────────────────────────────
// These match the events emitted by ChallengeFactory, IndividualChallenge,
// GroupChallenge, PublicChallenge, Reputation, and PublicGovernance.

const FACTORY_ADDRESS   = (process.env.FACTORY_ADDRESS   ?? "").toLowerCase();
const GOVERNANCE_ADDRESS = (process.env.GOVERNANCE_ADDRESS ?? "").toLowerCase();
const REPUTATION_ADDRESS = (process.env.REPUTATION_ADDRESS ?? "").toLowerCase();

// Topics for events we care about — processor will fetch only these logs.
// Computed with: ethers.id("EventName(arg1Type,arg2Type,...)")
const topics = {
  // Factory
  ChallengeCreated:  "0x..." as string, // fill after compile: keccak256("ChallengeCreated(uint256,address,address,uint8,uint8,string,string,uint256,uint256,uint256)")
  // Individual challenge
  BetPlaced:         "0x..." as string, // keccak256("BetPlaced(address,bool,uint256,uint256,uint256,uint256)")
  // All challenges
  ParticipantRegistered: "0x..." as string, // keccak256("ParticipantRegistered(address,uint256,uint256)")
  StateChanged:      "0x..." as string, // keccak256("StateChanged(uint8,uint8,uint256)")
  Settled:           "0x..." as string, // keccak256("Settled(uint256,uint256,uint256,uint256,uint256)")
  ParticipantSettled:"0x..." as string, // keccak256("ParticipantSettled(address,bool,uint256,int256)")
  // Reputation
  ReputationUpdated: "0x..." as string, // keccak256("ReputationUpdated(address,int256,int256,address,uint256)")
  // Governance
  EpochTicked:       "0x..." as string, // keccak256("EpochTicked(uint256,uint256,string,address,uint256)")
  Voted:             "0x..." as string, // keccak256("Voted(address,uint256,uint256,uint256)")
} as const;

// ─── Processor setup ──────────────────────────────────────────────────────

const processor = new EvmBatchProcessor()
  .setGateway("https://v2.archive.subsquid.io/network/ethereum-sepolia")
  .setRpcEndpoint({
    url: process.env.SEPOLIA_RPC_URL ?? "",
    rateLimit: 10,
  })
  .setFinalityConfirmation(75)
  .addLog({
    address: [FACTORY_ADDRESS],
    topic0: [topics.ChallengeCreated],
  })
  .addLog({
    // Listen to ALL addresses for individual challenge events — factory emits
    // the contract address in ChallengeCreated; we track dynamically below.
    topic0: [
      topics.BetPlaced,
      topics.ParticipantRegistered,
      topics.StateChanged,
      topics.Settled,
      topics.ParticipantSettled,
    ],
  })
  .addLog({
    address: [REPUTATION_ADDRESS],
    topic0: [topics.ReputationUpdated],
  })
  .addLog({
    address: [GOVERNANCE_ADDRESS],
    topic0: [topics.EpochTicked, topics.Voted],
  })
  .setBlockRange({ from: Number(process.env.START_BLOCK ?? 0) });

// ─── Entity imports (generated by squid-typeorm-codegen after schema) ─────
// import { Challenge, Bet, Participant, ReputationUpdate, UserReputation, EpochResult } from "./model";

// ─── Helpers ──────────────────────────────────────────────────────────────

function hexToAddress(hex: string): string {
  return "0x" + hex.slice(-40).toLowerCase();
}

function hexToUint256(hex: string): bigint {
  return BigInt(hex);
}

function hexToInt256(hex: string): bigint {
  const n = BigInt(hex);
  // two's complement for int256
  const MAX = BigInt("0x8000000000000000000000000000000000000000000000000000000000000000");
  return n >= MAX ? n - BigInt("0x10000000000000000000000000000000000000000000000000000000000000000") : n;
}

const CHALLENGE_TYPE_MAP: Record<number, string> = { 0: "INDIVIDUAL", 1: "GROUP", 2: "PUBLIC" };
const VERIFIER_TYPE_MAP:  Record<number, string> = { 0: "ON_CHAIN",   1: "API_ORACLE", 2: "AI_ORACLE" };
const STATE_MAP: Record<number, string> = { 0: "JOIN_OPEN", 1: "ACTIVE", 2: "VERIFY_PENDING", 3: "SETTLED" };

// ─── Main batch handler ───────────────────────────────────────────────────

// NOTE: Entity classes are generated after running `npm run codegen`.
// This file shows the full indexing logic — uncomment entity imports and
// db.upsert / db.save calls once codegen has been run.

processor.run(new TypeormDatabase({ supportHotBlocks: true }), async (ctx) => {
  // Track challenge addresses we've seen, so we know which log addresses are challenges
  // (loaded from DB on startup, extended as ChallengeCreated events come in)
  const knownChallenges = new Set<string>();

  for (const block of ctx.blocks) {
    for (const log of block.logs) {
      const addr = log.address.toLowerCase();
      const topic = log.topics[0];

      // ── ChallengeCreated (factory) ───────────────────────────────────
      if (addr === FACTORY_ADDRESS && topic === topics.ChallengeCreated) {
        // ABI decode: (uint256 challengeId, address contractAddress, address creator,
        //              uint8 challengeType, uint8 verifier, string title, string criteria,
        //              uint256 buyIn, uint256 joinDeadline, uint256 challengeDeadline)
        // Indexed: challengeId (topic1), contractAddress (topic2), creator (topic3)
        // Non-indexed: in log.data

        const challengeId       = hexToUint256(log.topics[1]);
        const contractAddress   = hexToAddress(log.topics[2]);
        const creator           = hexToAddress(log.topics[3]);

        // Decode ABI-encoded non-indexed data (simplified — use viem decodeEventLog in production)
        // data layout: uint8 challengeType, uint8 verifier, string title, string criteria,
        //              uint256 buyIn, uint256 joinDeadline, uint256 challengeDeadline
        const data = log.data.slice(2); // strip 0x
        const challengeTypeNum = parseInt(data.slice(0, 64), 16);
        const verifierNum      = parseInt(data.slice(64, 128), 16);
        // strings are dynamic — offsets at 128-191 and 192-255, actual data after
        const buyIn            = hexToUint256("0x" + data.slice(data.length - 192, data.length - 128));
        const joinDeadline     = hexToUint256("0x" + data.slice(data.length - 128, data.length - 64));
        const challengeDeadline = hexToUint256("0x" + data.slice(data.length - 64));

        knownChallenges.add(contractAddress);

        ctx.log.info(`ChallengeCreated: ${contractAddress} (id=${challengeId}, type=${CHALLENGE_TYPE_MAP[challengeTypeNum]})`);

        // TODO: after codegen
        // const challenge = new Challenge({ id: contractAddress, ... })
        // await ctx.store.upsert(challenge)
      }

      // ── BetPlaced (individual challenge) ────────────────────────────
      if (topic === topics.BetPlaced && knownChallenges.has(addr)) {
        const bettor = hexToAddress(log.topics[1]);
        const data   = log.data.slice(2);
        const side   = parseInt(data.slice(0, 64), 16) !== 0;
        const amount = hexToUint256("0x" + data.slice(64, 128));

        ctx.log.info(`BetPlaced: ${bettor} ${side ? "FOR" : "AGAINST"} ${amount} on ${addr}`);

        // TODO: after codegen
        // const bet = new Bet({ id: `${log.transactionHash}-${log.logIndex}`, ... })
        // await ctx.store.upsert(bet)
        // update challenge forPool / againstPool
      }

      // ── ParticipantRegistered ────────────────────────────────────────
      if (topic === topics.ParticipantRegistered && knownChallenges.has(addr)) {
        const participant = hexToAddress(log.topics[1]);
        const data        = log.data.slice(2);
        const stake       = hexToUint256("0x" + data.slice(0, 64));

        ctx.log.info(`ParticipantRegistered: ${participant} stake=${stake} on ${addr}`);
      }

      // ── StateChanged ─────────────────────────────────────────────────
      if (topic === topics.StateChanged && knownChallenges.has(addr)) {
        const data  = log.data.slice(2);
        const toNum = parseInt(data.slice(64, 128), 16);
        ctx.log.info(`StateChanged: ${addr} → ${STATE_MAP[toNum]}`);

        // TODO: ctx.store.upsert(update challenge state)
      }

      // ── ParticipantSettled ───────────────────────────────────────────
      if (topic === topics.ParticipantSettled && knownChallenges.has(addr)) {
        const participant = hexToAddress(log.topics[1]);
        const data        = log.data.slice(2);
        const won         = parseInt(data.slice(0, 64), 16) !== 0;
        const payout      = hexToUint256("0x" + data.slice(64, 128));
        const pnl         = hexToInt256("0x" + data.slice(128, 192));

        ctx.log.info(`ParticipantSettled: ${participant} won=${won} payout=${payout} pnl=${pnl}`);
      }

      // ── ReputationUpdated ────────────────────────────────────────────
      if (addr === REPUTATION_ADDRESS && topic === topics.ReputationUpdated) {
        const user      = hexToAddress(log.topics[1]);
        const challenge = hexToAddress(log.topics[2]);
        const data      = log.data.slice(2);
        const delta     = hexToInt256("0x" + data.slice(0, 64));
        const newScore  = hexToInt256("0x" + data.slice(64, 128));

        ctx.log.info(`ReputationUpdated: ${user} delta=${delta} newScore=${newScore}`);
      }

      // ── EpochTicked ──────────────────────────────────────────────────
      if (addr === GOVERNANCE_ADDRESS && topic === topics.EpochTicked) {
        const data                  = log.data.slice(2);
        const epoch                 = hexToUint256("0x" + data.slice(0, 64));
        const winningProposalIndex  = hexToUint256("0x" + data.slice(64, 128));
        // winningTitle is a dynamic string — offset at 128
        const publicChallengeAddress = hexToAddress("0x" + data.slice(192, 256));
        const prizePool              = hexToUint256("0x" + data.slice(256, 320));

        ctx.log.info(`EpochTicked: epoch=${epoch} winner=${publicChallengeAddress} prize=${prizePool}`);
      }
    }
  }
});
